
package com.employee_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeWSDL-service0", targetNamespace = "http://xmlns.example.com/1577780923363", wsdlLocation = "file:/D:/Development/eclipse_projects/EmployeeDetails/src/com/employee_service/EmployeeService.wsdl")
public class EmployeeWSDLService0
    extends Service
{

    private final static URL EMPLOYEEWSDLSERVICE0_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEWSDLSERVICE0_EXCEPTION;
    private final static QName EMPLOYEEWSDLSERVICE0_QNAME = new QName("http://xmlns.example.com/1577780923363", "EmployeeWSDL-service0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Development/eclipse_projects/EmployeeDetails/src/com/employee_service/EmployeeService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEWSDLSERVICE0_WSDL_LOCATION = url;
        EMPLOYEEWSDLSERVICE0_EXCEPTION = e;
    }

    public EmployeeWSDLService0() {
        super(__getWsdlLocation(), EMPLOYEEWSDLSERVICE0_QNAME);
    }

    public EmployeeWSDLService0(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEWSDLSERVICE0_QNAME, features);
    }

    public EmployeeWSDLService0(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEWSDLSERVICE0_QNAME);
    }

    public EmployeeWSDLService0(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEWSDLSERVICE0_QNAME, features);
    }

    public EmployeeWSDLService0(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeWSDLService0(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeMgr
     */
    @WebEndpoint(name = "EmployeeMgrEndpoint0")
    public EmployeeMgr getEmployeeMgrEndpoint0() {
        return super.getPort(new QName("http://xmlns.example.com/1577780923363", "EmployeeMgrEndpoint0"), EmployeeMgr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeMgr
     */
    @WebEndpoint(name = "EmployeeMgrEndpoint0")
    public EmployeeMgr getEmployeeMgrEndpoint0(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1577780923363", "EmployeeMgrEndpoint0"), EmployeeMgr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEWSDLSERVICE0_EXCEPTION!= null) {
            throw EMPLOYEEWSDLSERVICE0_EXCEPTION;
        }
        return EMPLOYEEWSDLSERVICE0_WSDL_LOCATION;
    }

}
